server:
  port: 10004

spring:
  datasource:
#    url: jdbc:h2:file:/var/lib/h2db/h2db;AUTO_SERVER=TRUE
    url: jdbc:h2:file:~/data/h2db/h2db;AUTO_SERVER=TRUE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
